### ISSUE TITLE
Issue while scanning large datasets

### ISSUE THREAD

**Issue by jonbonazza** [tsuna/gohbase#65] opened 2017-07-27 23:54 UTC
I am using the new scanner api like so:

```go
func ScanCh(scanner hrpc.Scanner, errCallbacks ...func(row *hrpc.Result, err error)) <-chan *hrpc.Result {
	ch := make(chan *hrpc.Result)
	go func() {
		defer close(ch)
		defer scanner.Close()
		var row *hrpc.Result
		var err error
		for err != io.EOF {
			if row, err = scanner.Next(); err == nil {
				ch <- row
			} else if err != io.EOF {
				for _, f := range errCallbacks {
					f(row, err)
				}
			}
		}
	}()
	return ch
}
```

After some minutes and several hundred rows being scanned, I am seeing the following error from HBase: 

```
ERRO[0249] failed to close scanner                       err="HBase Java exception org.apache.hadoop.hbase.UnknownScannerException:
org.apache.hadoop.hbase.UnknownScannerException: Name: 1282974, already closed?
        at org.apache.hadoop.hbase.regionserver.RSRpcServices.scan(RSRpcServices.java:2128)
        at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:32205)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2034)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:107)
        at org.apache.hadoop.hbase.ipc.RpcExecutor.consumerLoop(RpcExecutor.java:130)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$1.run(RpcExecutor.java:107)
        at java.lang.Thread.run(Thread.java:745)
" scannerID=1282974
```

It should also be noted that this error occurs well before all of the rows are scanned, so I never get to scan all rows.

**Comment by jonbonazza** [comment] 2017-07-31 18:51
@timoha this also occurs when using the scanner API directly and not using a channel. Any idea what is going on here? For context, for each cell in the scan, I am doing a cockroachdb database insertion. Is it possible that this operation is taking too long and the client is timing out?

**Comment by timoha** [comment] 2017-08-09 23:59
I'll try to investigate soon, been a bit occupied. The error that you are seeing should not affect anything in your code, as it happens in the background. Would be more useful if you provided the error that is returned by call to Next().

**Comment by jonbonazza** [comment] 2017-08-17 20:41
@timoha Interesting... I thought that was the error that was being returned by the Next() call. Unless, maybe, an ```io.EOF``` error is being returned. I'll investigate more once I get the chance.

**Comment by jonbonazza** [comment] 2017-10-25 20:37
@timoha the call to Next() I am getting is ```io.EOF```.
Sorry for the (very) late reply here.

**Comment by jonbonazza** [comment] 2017-10-25 21:22
@timoha the [docs](https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/UnknownScannerException.html) for ```UnknownScannerException``` seem to suggest the client isn't "checking in" with the server and the server is closing the connection.

**Comment by jonbonazza** [comment] 2017-10-25 23:19
More information. Looks like when I see this UnknownScannerException, **only that one rpc fails**. If there are more RPCs to make, then they will continue on, but I will have lost the data (save some partial data that is returned, if any) for the failed RPC. Not really sure how to recover from this.

**Comment by timoha** [comment] 2017-11-06 19:17
Yeah, sound like you either take a long time between calling Next() or your regionserver died in the process of scanning.

For the first case, we could implement periodic scanner lease renewal: https://github.com/tsuna/gohbase/blob/master/pb/Client.proto#L285

For the second case, need to spend some time to better handle error cases for scanner and retry in case we get this exception gracefully. I might have some time soon, to take a stab at it.

**Comment by jonbonazza** [comment] 2017-11-06 21:47
@timoha I was able to confirm that it is the former. In this event will it miss data? If so, I am not sure what I can do here as we have, like, gigs of data that is being processed concurrently, distributed across nodes, but in order to not destroy our memory, we throttle the number of goroutines with a semaphore. If we crank this sempahore up too high, we end up pegging the CPU and stalling the system, so we have to have a balance.

How difficult would it be to implement lease renewal?

**Comment by jonbonazza** [comment] 2018-05-13 18:04
@timoha We are again encountering this time, we are not doing anything heavy, but we are doing _a lot_ of scanning and inserting. I am worried we are overloading the cluster and I was wondering.. What happens in the event that the HBase cluster is overloaded and a request to the cluster takes a long time? Will the lease still expire because Next() hasn't been called in a bit? If so, what can we do here? (Aside from throw more resources at the HBase cluster.)

**Comment by apleshi** [comment] 2018-05-15 10:48
same issue with me, scanner returned partial results than hbase shell. 
@jonbonazza could you please share your solution with me.

**Comment by tsuna** [comment] 2021-11-12 14:08
`UnknownScannerException` is handled gracefully both in [AsyncHBase](https://github.com/OpenTSDB/asynchbase/blob/000f4216c520907dcbdd20be761a168e1ccbb5b0/src/Scanner.java#L856) and in the [standard HBase client](https://github.com/apache/hbase/blob/rel/2.4.8/hbase-client/src/main/java/org/apache/hadoop/hbase/client/ClientScanner.java#L354), so maybe we should do that too here.

**Comment by timoha** [comment] 2021-11-13 02:50
Haven't checked AsyncHBase code or standard client code in a while, but previously neither actually handled the case of partial row scanners. The problem is that if the scanner times out in the middle of the row, there's no way to safely (preserving row atomicity) restart scanning from the middle of the row. The best option has always been for clients to explicitly keep track of the last row they've scanned and restart scanning from the beginning of the row when exception happens. That way each client can take care of duplicates their own way.

That being said, maybe there's an API that somehow uses MVCC to properly address this now, but scanners can blow up with OOM if you don't rely on partial row scanning feature.

**Comment by dethi** [comment] 2023-03-28 19:10
Closing in favour of #91

**Closed by dethi** 2023-03-28 19:10 UTC
