### ISSUE TITLE
Can't query system tables

### ISSUE THREAD

**Issue by ozkatz** [tsuna/gohbase#23] opened 2017-01-07 22:48 UTC
When I try to perform a Scan or a Get operation against a system table (e.g. `hbase:namespace` or `hbase:meta`), I get back the following error:

```
WTF: Meta returned an entry for the wrong table!  Looked up table="hbase:namespace" key="default" got region=*region.info{Table: "namespace", Name: "hbase:namespace,,1479305903740.2ef03b3d1421dd63dd7774cd115039cb.", StopKey: ""}
```

It seems that the table name returned by HBase doesn't include the `"hbase:"` prefix so it fails [this check](https://github.com/tsuna/gohbase/blob/c00ed13b09988df7bfcab9959feebb9c0d77bbff/rpc.go#L303).
Not sure how to go about fixing this though.

**Comment by Timoha** [comment] 2017-02-07 00:46
What's your hbase version?
I'm on `1.2.4` standalone setup, and I was able to reproduce `hbase:namespace` issue. 
However, it works as expected for `hbase:meta`.

**Comment by Timoha** [comment] 2017-02-07 01:01
Looks like the bug is [here](https://github.com/tsuna/gohbase/blob/master/region/info.go#L73):

We should add `Namespace` field to `regionInfo`. Then when we go through [this check](https://github.com/tsuna/gohbase/blob/c00ed13b09988df7bfcab9959feebb9c0d77bbff/rpc.go#L303), check if requested table is of format `<namespace>:<table>` and compare them appropriately.

**Comment by ozkatz** [comment] 2017-02-08 22:55
@Timoha I'm using HBase 1.2.0 (as distributed by Cloudera)

**Comment by Timoha** [comment] 2017-03-08 19:58
should be fixed by https://github.com/tsuna/gohbase/commit/31c6161099f043b34b4111bf1a6ff53a87fb998a. Thanks!

**Closed by Timoha** 2017-03-08 19:58 UTC
