### ISSUE TITLE
NewClient() got errors 

### ISSUE THREAD

**Issue by wanderself** [tsuna/gohbase#41] opened 2017-04-03 20:15 UTC
```
time="2017-04-03T17:50:22+08:00" level=error msg="failed looking up region" backoff=16ms err="deadline exceeded" key=1 table=test 
time="2017-04-03T17:50:52+08:00" level=error msg="failed looking up region" backoff=32ms err="deadline exceeded" key=1 table=test 
time="2017-04-03T17:51:22+08:00" level=error msg="failed looking up region" backoff=64ms err="deadline exceeded" key=1 table=test 
time="2017-04-03T17:51:52+08:00" level=error msg="failed looking up region" backoff=128ms err="deadline exceeded" key=1 table=test 
time="2017-04-03T17:52:22+08:00" level=error msg="failed looking up region" backoff=256ms err="deadline exceeded" key=1 table=test 
time="2017-04-03T17:52:52+08:00" level=error msg="failed looking up region" backoff=512ms err="deadline exceeded" key=1 table=test 
time="2017-04-03T17:53:23+08:00" level=error msg="failed looking up region" backoff=1.024s err="deadline exceeded" key=1 table=test 
time="2017-04-03T17:53:54+08:00" level=error msg="failed looking up region" backoff=2.048s err="deadline exceeded" key=1 table=test 
time="2017-04-03T17:54:26+08:00" level=error msg="failed looking up region" backoff=4.096s err="deadline exceeded" key=1 table=test 
time="2017-04-03T17:55:00+08:00" level=error msg="failed looking up region" backoff=8.192s err="deadline exceeded" key=1 table=test 
time="2017-04-03T17:55:33+08:00" level=info msg="added new region client" client=RegionClient{Host: yakkety, Port: 40285} 
time="2017-04-03T17:55:33+08:00" level=info msg="added new region" overlaps=[] region=RegionInfo{Name: test,,1491097549520.89c4b68edcedd43f93accb5eb87574b7., ID: 1491097549520, Namespace: , Table: test, StartKey: , StopKey: } replaced=true 
res:  &{[0xc04223c820 0xc04223c8c0] <nil> 0xc042034ce0}
```

my test code 
```
func main() {
	client := gohbase.NewClient("192.168.0.106")

	getRequest, err := hrpc.NewGetStr(context.Background(), "test", "1")
	if err != nil {
		log.Println(err.Error())
		return
	}
	getRsp, err := client.Get(getRequest)
	if err != nil {
		log.Println(err.Error())
		return
	}
	fmt.Println("res: ", getRsp)

}
```

**Comment by Timoha** [comment] 2017-04-04 02:25
I'm assuming you are referring to errors printed in logs because you got the response as expected without getting returned an error anywhere.

Those errors mean that gohbase didn't get any response from regionserver holding hbase:meta table for a total of 5 minutes! It looks like the issue is on your side (slow network, etc).

I'm going to close the issue since gohbase worked here as expected although we could improve the logging (which is a separate issue). Hope this explains it.

**Closed by Timoha** 2017-04-04 02:25 UTC

**Comment by wanderself** [comment] 2017-04-06 23:57
thx guy, 
I found out the key points of this issue--"unkown host".
grateful gaze for your project(*^_^*)
