### ISSUE TITLE
nil pointer

### ISSUE THREAD

**Issue by mitiger** [tsuna/gohbase#38] opened 2017-02-24 07:35 UTC
![image](https://cloud.githubusercontent.com/assets/1697699/23294460/8b5e17de-faa6-11e6-86bf-cecde4b10a0d.png)

![image](https://cloud.githubusercontent.com/assets/1697699/23294536/d0ce84ca-faa6-11e6-8670-f24b85637826.png)

file: region/client.go , function  (c *client) sendBatch()  , i hava encounter  nil pointer ,

what's wrong with me?

**Comment by Timoha** [comment] 2017-02-24 18:07
This is due to using [`filepath.Join()`](https://github.com/tsuna/gohbase/blob/master/zk/client.go#L39) when prepending to the path (introduced in #32). I assume you are running on Windows, so it rewrites all `/` with `\`. Didn't see that coming, I'll send a fix soon.

The `panic` that you are seeing is a different bug though that probably got exposed by this change is because we don't set any `Context` for the admin region. Will fix as well with a test.

> what's wrong with me?

nothing is wrong with you @mitiger :) Maybe you could try using some older commit for now?

**Comment by mitiger** [comment] 2017-02-25 01:54
go version go1.6.3 windows/amd64
hbase-1.2.4

i just put data to hbase for 380 goroutine together .
also set queue option to 500.

my code are as follows:


cluster, err := hbase.GetDefaultCluster()
	fmt.Println("cluster:", cluster)
	if err != nil {
		fmt.Println("--->get cluster:", err)
		return err
	}

	values := map[string]map[string][]byte{
		"data": map[string][]byte{
			"": []byte("3.22222"),
		},
	}

	put, err := hrpc.NewPutStr(context.Background(), "t_elec_data", fmt.Sprintf("%d_%d", time.Now().UnixNano(), num), values)
	if err != nil {
		fmt.Println("new put error:", err)
		return err
	}

	begin := time.Now().UnixNano() / 1000000
	_, err = cluster.Client.Put(put)
	if err != nil {
		fmt.Println("write data to hbase error:", err)
		return err
	}
	end := time.Now().UnixNano() / 1000000

	fmt.Println("---->  write hbase time:", end-begin, " ms, thread:", num, "count:", count)
	return nil

**Comment by Timoha** [comment] 2017-02-27 20:20
Alright, I found the root cause, should be fixed by https://github.com/tsuna/gohbase/commit/b66b28c46ff1131b2a91208fb3b53ec5657a6c6a. It was a problem with not reseting a batch slice on a failure case. Thanks for reporting this!

**Closed by Timoha** 2017-02-27 20:20 UTC
